const clamp = (value, min, max) => Math.max(min, Math.min(max, value));

export function createAudio() {
  let context = null, master = null, ambience = null, running = false, paused = false, muted = false, volume = .24, motifTimer = 0, windSource = null, seaSource = null, lastWarning = 0, lastRunKey = '';
  const active = new Set(), motifSources = new Set();
  const AudioContextClass = () => globalThis.AudioContext || globalThis.webkitAudioContext;
  const output = () => { if (master) master.gain.setTargetAtTime(muted || volume <= 0 ? 0 : volume, context.currentTime, .025); };
  function ensure() { if (context) return true; const AudioClass = AudioContextClass(); if (!AudioClass) return false; try { context = new AudioClass(); master = context.createGain(); master.gain.value = 0; master.connect(context.destination); output(); return true; } catch (_) { context = null; master = null; return false; } }
  function unlock() { if (!ensure()) return false; try { const result = context.resume?.(); if (result?.catch) result.catch(() => {}); return true; } catch (_) { return false; } }
  function tone(frequency, duration = .16, type = 'sine', gain = .08, when = null, endFrequency = null, trackSet = null) { if (!context || !master || muted || volume <= 0) return; const start = Math.max(context.currentTime + .005, when ?? context.currentTime + .005), oscillator = context.createOscillator(), envelope = context.createGain(); oscillator.type = type; oscillator.frequency.setValueAtTime(frequency, start); if (endFrequency) oscillator.frequency.exponentialRampToValueAtTime(Math.max(20, endFrequency), start + duration); envelope.gain.setValueAtTime(.0001, start); envelope.gain.exponentialRampToValueAtTime(gain, start + .018); envelope.gain.exponentialRampToValueAtTime(.0001, start + duration); oscillator.connect(envelope).connect(master); oscillator.start(start); oscillator.stop(start + duration + .03); active.add(oscillator); trackSet?.add(oscillator); const cleanup = () => { oscillator.disconnect?.(); envelope.disconnect?.(); active.delete(oscillator); trackSet?.delete(oscillator); }; if (oscillator.addEventListener) oscillator.addEventListener('ended', cleanup, { once: true }); else oscillator.onended = cleanup; }
  function startAmbience() { if (!context || windSource || seaSource) return; ambience = context.createGain(); ambience.gain.value = .16; ambience.connect(master); const length = Math.max(1, Math.floor(context.sampleRate * 2)); const buffer = context.createBuffer(1, length, context.sampleRate), data = buffer.getChannelData(0); for (let i = 0; i < length; i++) data[i] = (Math.random() * 2 - 1) * .34; windSource = context.createBufferSource(); windSource.buffer = buffer; windSource.loop = true; const windFilter = context.createBiquadFilter(); windFilter.type = 'lowpass'; windFilter.frequency.value = 620; const windGain = context.createGain(); windGain.gain.value = .045; windSource.connect(windFilter).connect(windGain).connect(ambience); windSource.start(); active.add(windSource); const seaOsc = context.createOscillator(); seaOsc.type = 'sine'; seaOsc.frequency.value = 68; const seaGain = context.createGain(); seaGain.gain.value = .018; seaOsc.connect(seaGain).connect(ambience); seaOsc.start(); seaSource = seaOsc; active.add(seaOsc); scheduleMotif(); }
  function scheduleMotif() { if (!running || !context || paused) return; const now = context.currentTime + .04, notes = [220, 277.18, 329.63, 277.18]; notes.forEach((note, index) => tone(note, .7, 'triangle', .026, now + index * .54, note * 1.01, motifSources)); motifTimer = globalThis.setTimeout(scheduleMotif, 2500); }
  function clearMotifTimer() { if (motifTimer) { globalThis.clearTimeout(motifTimer); motifTimer = 0; } }
  function start() { if (!unlock()) return false; if (running) return true; running = true; paused = false; lastWarning = 0; startAmbience(); return true; }
  function pause() { clearMotifTimer(); for (const source of motifSources) { try { source.stop?.(); } catch (_) {} try { source.disconnect?.(); } catch (_) {} active.delete(source); } motifSources.clear(); if (!context) return; paused = true; try { const result = context.suspend?.(); if (result?.catch) result.catch(() => {}); } catch (_) {} }
  function resume() { if (!context || !running) return; paused = false; try { const result = context.resume?.(); if (result?.catch) result.catch(() => {}); } catch (_) {} if (!motifTimer) scheduleMotif(); }
  function stop() { running = false; paused = false; lastWarning = 0; lastRunKey = ''; clearMotifTimer(); for (const source of active) { try { source.stop?.(); } catch (_) {} try { source.disconnect?.(); } catch (_) {} } active.clear(); motifSources.clear(); windSource = null; seaSource = null; ambience?.disconnect?.(); ambience = null; }
  function play(event, detail = {}) { if (!context && !unlock()) return false; const kind = typeof event === 'string' ? event : event?.type || event?.id || ''; if (muted || volume <= 0 || paused) return true; const now = context.currentTime; if (kind === 'placed' || kind === 'place') { tone(523.25, .13, 'triangle', .12, now); tone(783.99, .2, 'sine', .07, now + .045); } else if (kind === 'denied' || kind === 'error') tone(130, .16, 'square', .07, now, 98); else if (kind === 'arrival') { tone(392, .2, 'triangle', .1, now); tone(587.33, .35, 'triangle', .09, now + .11); } else if (kind === 'stage-clear') { [392, 493.88, 659.25].forEach((n, i) => tone(n, .35, 'triangle', .08, now + i * .12)); } else if (kind === 'win') { [261.63, 329.63, 392, 523.25].forEach((n, i) => tone(n, .5, 'sine', .09, now + i * .14)); } else if (kind === 'lose') { tone(220, .42, 'sawtooth', .08, now, 92); } else if (kind === 'tilt' || kind === 'flood' || kind === 'warning') { tone(kind === 'flood' ? 118 : 176, .16, 'sine', .045, now, kind === 'flood' ? 102 : 145); } else if (kind === 'launch') tone(330, .25, 'triangle', .08, now, 540); else if (detail?.frequency) tone(Number(detail.frequency), Number(detail.duration) || .15, 'sine', .06, now); return true; }
  function update(run) { if (!running || !run || paused) return; const runKey = `${run.voyageId || ''}:${run.stageIndex ?? ''}`; if (runKey !== lastRunKey) { lastRunKey = runKey; lastWarning = 0; } const danger = Math.max(Math.abs(Number(run.roll) || 0), Math.abs(Number(run.pitch) || 0)) > .42 || Number(run.water) > .7; const now = context?.currentTime || 0; if (danger && now - lastWarning > 1.2) { lastWarning = now; play(Number(run.water) > .7 ? 'flood' : 'tilt'); } }
  function setVolume(value) { volume = clamp(Number(value) || 0, 0, 1); output(); }
  function setMuted(value) { muted = !!value; output(); }
  function dispose() { stop(); try { const result = context?.close?.(); if (result?.catch) result.catch(() => {}); } catch (_) {} context = null; master = null; }
  return { unlock, setVolume, setMuted, start, pause, resume, stop, play, update, dispose };
}

export default createAudio;
