import * as THREE from 'three';
import { TUNING, cellToWorld, worldToCell } from './voyages.js';
import { createBallastTank, createDeck, createGantry, createResident, createStructure, disposeModel, palette } from './models.js';

const CELL = () => TUNING.cell;
const SIZE = () => TUNING.size;
const HALF_DECK = () => TUNING.halfDeck;
const SEA_LEVEL = () => 0;
const clamp = (value, min, max) => Math.max(min, Math.min(max, value));

function disposeObject(root) { if (!root) return; const geometries = new Set(), materials = new Set(); root.traverse((object) => { if (object.geometry) geometries.add(object.geometry); const list = Array.isArray(object.material) ? object.material : object.material ? [object.material] : []; list.forEach((material) => materials.add(material)); }); geometries.forEach((geometry) => geometry.dispose()); materials.forEach((material) => material.dispose()); root.clear(); }
function cellPosition(col, row) { return cellToWorld(col, row); }

class TenderScene {
  constructor(container) {
    this.host = container; this.canvas = container?.tagName === 'CANVAS' ? container : container?.querySelector?.('canvas') || (typeof document !== 'undefined' ? document.createElement('canvas') : null); if (!this.canvas) throw new Error('Tenderweight requires a canvas'); if (container?.tagName !== 'CANVAS' && this.canvas.parentElement !== container && container?.appendChild) container.appendChild(this.canvas);
    this.frame = 0; this.elapsed = 0; this.voyage = null; this.run = null; this.structureMap = new Map(); this.residentMap = new Map(); this.structureCount = 0; this.residentCount = 0; this.boatRoll = 0; this.boatPitch = 0;
    this.renderer = new THREE.WebGLRenderer({ canvas: this.canvas, antialias: false, powerPreference: 'high-performance' }); this.renderer.outputColorSpace = THREE.SRGBColorSpace; this.renderer.toneMapping = THREE.ACESFilmicToneMapping; this.renderer.toneMappingExposure = 1.08;
    const gl = this.renderer.getContext(); let rendererName = ''; try { const ext = gl.getExtension('WEBGL_debug_renderer_info'); rendererName = ext ? gl.getParameter(ext.UNMASKED_RENDERER_WEBGL) : gl.getParameter(gl.RENDERER); } catch (_) {} this.software = /swiftshader|llvmpipe|software|mesa/i.test(`${rendererName} ${globalThis.navigator?.userAgent || ''}`); this.pixelBudget = this.software ? 400000 : 2000000; this.renderer.shadowMap.enabled = !this.software; this.renderer.shadowMap.type = THREE.PCFSoftShadowMap;
    this.scene = new THREE.Scene(); this.scene.background = new THREE.Color(0xdff5f0); this.scene.fog = new THREE.Fog(0xdff5f0, 35, 85); this.world = new THREE.Group(); this.scene.add(this.world); this.camera = new THREE.PerspectiveCamera(42, 16 / 9, .1, 140); this.camera.position.set(0, 15, 19); this.camera.lookAt(0, .15, 0); this.scene.add(this.camera); this.addLighting(); this.createSea(); this.boat = new THREE.Group(); this.boat.name = 'floating-village'; this.world.add(this.boat); this.deck = createDeck(); this.boat.add(this.deck); this.gantry = createGantry(); this.boat.add(this.gantry); this.tank = createBallastTank(); this.boat.add(this.tank); this.markShadows(this.deck); this.markShadows(this.gantry); this.markShadows(this.tank); this.createPickPlane(); this.createCursor(); this.resize(); this.resizeObserver = globalThis.ResizeObserver ? new ResizeObserver(() => this.resize()) : null; this.resizeObserver?.observe(this.host || this.canvas);
  }
  addLighting() { this.scene.add(new THREE.HemisphereLight(0xffffff, 0x79a6a5, 2.2)); const key = new THREE.DirectionalLight(0xfff2ce, 3.2); key.position.set(-12, 24, 18); key.castShadow = !this.software; key.shadow.mapSize.set(1024, 1024); key.shadow.camera.left = -18; key.shadow.camera.right = 18; key.shadow.camera.top = 22; key.shadow.camera.bottom = -12; key.shadow.camera.near = .5; key.shadow.camera.far = 90; this.scene.add(key); this.keyLight = key; }
  markShadows(root) { if (!root) return; root.traverse((object) => { if (object.isMesh) { object.castShadow = !this.software; object.receiveShadow = true; } }); }
  createSea() { const sea = new THREE.Mesh(new THREE.PlaneGeometry(150, 150), new THREE.MeshStandardMaterial({ color: palette.sea, roughness: .5, metalness: .08 })); sea.rotation.x = -Math.PI / 2; sea.position.y = SEA_LEVEL(); sea.receiveShadow = true; sea.name = 'world-sea'; this.world.add(sea); this.sea = sea; const wavePositions = []; for (let row = -7; row <= 7; row++) for (let col = -7; col <= 7; col++) { const x = col * 7.2, z = row * 6.4; wavePositions.push(x - 1.2, SEA_LEVEL() + .012, z, x + 1.2, SEA_LEVEL() + .012, z + .18 * Math.sin(col * 1.7 + row)); } const waveGeometry = new THREE.BufferGeometry(); waveGeometry.setAttribute('position', new THREE.Float32BufferAttribute(wavePositions, 3)); const waves = new THREE.LineSegments(waveGeometry, new THREE.LineBasicMaterial({ color: palette.foam, transparent: true, opacity: .34 })); waves.name = 'sea-foam'; this.world.add(waves); this.waves = waves; this.waveBase = wavePositions; }
  createPickPlane() { const size = HALF_DECK() * 2; this.pickPlane = new THREE.Mesh(new THREE.PlaneGeometry(size, size), new THREE.MeshBasicMaterial({ color: 0xffffff, transparent: true, opacity: 0, depthWrite: false, side: THREE.DoubleSide })); this.pickPlane.rotation.x = -Math.PI / 2; this.pickPlane.position.y = .14; this.pickPlane.name = 'deck-pick-surface'; this.boat.add(this.pickPlane); }
  createCursor() { this.cursorMesh = new THREE.Mesh(new THREE.RingGeometry(.48, .61, 4), new THREE.MeshBasicMaterial({ color: palette.yellowBright, transparent: true, opacity: .9, side: THREE.DoubleSide, depthTest: false })); this.cursorMesh.rotation.x = -Math.PI / 2; this.cursorMesh.position.y = .17; this.cursorMesh.visible = false; this.cursorMesh.renderOrder = 5; this.cursorMesh.name = 'build-cursor'; this.boat.add(this.cursorMesh); }
  setVoyage(voyage) { this.voyage = voyage || null; this.run = null; this.clearDynamic(); this.elapsed = 0; }
  clearDynamic() { for (const object of this.structureMap.values()) { object.parent?.remove(object); disposeModel(object); } for (const object of this.residentMap.values()) { object.parent?.remove(object); disposeModel(object); } this.structureMap.clear(); this.residentMap.clear(); this.structureCount = 0; this.residentCount = 0; }
  structurePosition(structure) { if (Number.isFinite(structure.x) && Number.isFinite(structure.z)) return structure; return cellPosition(structure.col, structure.row); }
  syncStructures(run) { const structures = Array.isArray(run.structures) ? run.structures : [], wanted = new Set(structures.map((structure) => structure.id)), occupants = new Map(); for (const resident of Array.isArray(run.residents) ? run.residents : []) if (resident.cabinId) occupants.set(resident.cabinId, (occupants.get(resident.cabinId) || 0) + 1); for (const [id, object] of this.structureMap) if (!wanted.has(id)) { object.parent?.remove(object); disposeModel(object); this.structureMap.delete(id); } for (const structure of structures) { const position = this.structurePosition(structure); let object = this.structureMap.get(structure.id); if (!object || object.userData.type !== structure.type) { if (object) { object.parent?.remove(object); disposeModel(object); } object = createStructure(structure.type); object.userData.type = structure.type; object.name = `structure-${structure.id}`; this.markShadows(object); this.boat.add(object); this.structureMap.set(structure.id, object); } object.position.set(position.x, 0, position.z); object.userData.col = structure.col; object.userData.row = structure.row; if (structure.type === 'cabin') object.userData.capacityMarkers?.forEach((marker, index) => { marker.visible = index < (occupants.get(structure.id) || 0); }); } this.structureCount = this.structureMap.size; }
  syncResidents(run) { const residents = Array.isArray(run.residents) ? run.residents : [], wanted = new Set(residents.map((resident) => resident.id)); for (const [id, object] of this.residentMap) if (!wanted.has(id)) { object.parent?.remove(object); disposeModel(object); this.residentMap.delete(id); } for (const [index, resident] of residents.entries()) { let object = this.residentMap.get(resident.id); if (!object) { object = createResident(index); object.userData.residentId = resident.id; this.markShadows(object); this.boat.add(object); this.residentMap.set(resident.id, object); } let x = Number.isFinite(resident.x) ? resident.x : 0, z = Number.isFinite(resident.z) ? resident.z : 0; if (resident.settled && resident.cabinId) { const cabin = this.structureMap.get(resident.cabinId); const structure = Array.isArray(run.structures) ? run.structures.find((candidate) => candidate.id === resident.cabinId) : null; if (cabin && structure) { const cabinPosition = this.structurePosition(structure), offset = ((index % 3) - 1) * .22; x = cabinPosition.x + offset; z = cabinPosition.z + (Math.floor(index / 3) % 2 ? .2 : -.2); } } object.position.set(x, .155, z); object.userData.settled = !!resident.settled; object.userData.phase = index * .9; } this.residentCount = this.residentMap.size; }
  updateCursor(cursor) { if (!cursor || !Number.isFinite(cursor.col) || !Number.isFinite(cursor.row)) { this.cursorMesh.visible = false; return; } const position = cellPosition(cursor.col, cursor.row); this.cursorMesh.position.set(position.x, .17, position.z); this.cursorMesh.material.color.set(cursor.valid ? palette.yellowBright : palette.coralDark); this.cursorMesh.visible = true; }
  pick(clientX, clientY) { const rect = this.canvas.getBoundingClientRect(); if (!rect.width || !rect.height) return null; const ndc = new THREE.Vector2((clientX - rect.left) / rect.width * 2 - 1, -((clientY - rect.top) / rect.height) * 2 + 1); const raycaster = new THREE.Raycaster(); raycaster.setFromCamera(ndc, this.camera); const hit = raycaster.intersectObject(this.pickPlane, false)[0]; if (!hit) return null; const local = this.boat.worldToLocal(hit.point.clone()), cell = worldToCell(local.x, local.z), size = SIZE(); return cell && cell.col >= 0 && cell.col < size && cell.row >= 0 && cell.row < size ? cell : null; }
  update(run, dt = 1 / 60, cursor = null) { if (!run) return; const delta = clamp(Number(dt) || 0, 0, .1); this.run = run; this.elapsed += delta; this.boat.position.y = Number.isFinite(run.freeboard) ? run.freeboard : .52; this.boat.rotation.x = Number(run.pitch) || 0; this.boat.rotation.z = -(Number(run.roll) || 0); this.boatRoll = Number(run.roll) || 0; this.boatPitch = Number(run.pitch) || 0; this.syncStructures(run); this.syncResidents(run); this.tank.position.set(run.tank?.x || 0, (this.gantry.userData.tankY || 3.72) + Math.sin(this.elapsed * 2.2) * .025, run.tank?.z || 0); this.tank.rotation.z = Math.sin(this.elapsed * 2.2) * .03; if (this.gantry.userData.crossbar) this.gantry.userData.crossbar.position.z = run.tank?.z || 0; if (this.waves?.geometry?.attributes?.position) { const positions = this.waves.geometry.attributes.position.array; for (let i = 0; i < positions.length; i += 6) { const phase = i * .045; positions[i] = this.waveBase[i] + Math.sin(this.elapsed * .45 + phase) * .11; positions[i + 2] = this.waveBase[i + 2] + Math.cos(this.elapsed * .38 + phase) * .08; positions[i + 3] = this.waveBase[i + 3] + Math.sin(this.elapsed * .45 + phase + .5) * .11; positions[i + 5] = this.waveBase[i + 5] + Math.cos(this.elapsed * .38 + phase + .5) * .08; } this.waves.geometry.attributes.position.needsUpdate = true; } this.updateCursor(cursor); this.animateResidents(delta); this.render(); }
  animateResidents() { for (const object of this.residentMap.values()) { const phase = this.elapsed * (object.userData.settled ? .6 : 2.4) + (object.userData.phase || 0); object.position.y = .155 + Math.sin(phase) * (object.userData.settled ? .018 : .02); object.rotation.y = Math.sin(phase * .55) * .12; const left = object.getObjectByName('leg--1'), right = object.getObjectByName('leg-1'); if (left) left.rotation.x = Math.sin(phase * 2) * .18; if (right) right.rotation.x = -Math.sin(phase * 2) * .18; } }
  render() { this.renderer.render(this.scene, this.camera); this.frame++; }
  resize() { const width = this.canvas.clientWidth || this.host?.clientWidth || 960, height = this.canvas.clientHeight || this.host?.clientHeight || 540; this.renderer.setPixelRatio(Math.min(2, globalThis.devicePixelRatio || 1, Math.sqrt(this.pixelBudget / Math.max(1, width * height)))); this.renderer.setSize(width, height, false); this.camera.aspect = width / Math.max(1, height); this.camera.updateProjectionMatrix(); const targetY = 1.6, boundX = Math.max(HALF_DECK() + .5, 5.9), boundZ = boundX, minY = -.2, maxY = 5.3, corners = []; for (const x of [-boundX, boundX]) for (const y of [minY, maxY]) for (const z of [-boundZ, boundZ]) corners.push(new THREE.Vector3(x, y, z)); let fit = height < 600 ? .8 : 1; for (let pass = 0; pass < 8; pass++) { this.camera.position.set(0, targetY + 15 * fit, 19 * fit); this.camera.lookAt(0, targetY, 0); this.camera.updateMatrixWorld(true); const projected = corners.map((corner) => corner.clone().project(this.camera)), extent = Math.max(...projected.map((point) => Math.max(Math.abs(point.x), Math.abs(point.y)))); if (extent <= .92) break; fit *= extent / .92 * 1.015; } this.camera.position.set(0, targetY + 15 * fit, 19 * fit); this.camera.lookAt(0, targetY, 0); this.camera.updateProjectionMatrix(); }
  projectedDeck() { const width = this.canvas.clientWidth || this.host?.clientWidth || 960, height = this.canvas.clientHeight || this.host?.clientHeight || 540, rect = this.canvas.getBoundingClientRect?.() || { left: 0, top: 0 }, cells = [], size = SIZE(); this.boat.updateMatrixWorld(true); const toPage = (point) => ({ x: rect.left + (point.x + 1) * width / 2, y: rect.top + (1 - point.y) * height / 2 }); for (let row = 0; row < size; row++) for (let col = 0; col < size; col++) { const local = cellPosition(col, row), point = new THREE.Vector3(local.x, .14, local.z).applyMatrix4(this.boat.matrixWorld).project(this.camera); cells.push({ col, row, ...toPage(point) }); } const corners = [[-HALF_DECK(), .14, -HALF_DECK()], [HALF_DECK(), .14, -HALF_DECK()], [-HALF_DECK(), .14, HALF_DECK()], [HALF_DECK(), .14, HALF_DECK()]].map(([x, y, z]) => new THREE.Vector3(x, y, z).applyMatrix4(this.boat.matrixWorld).project(this.camera)).map(toPage); return { cells, bounds: { left: Math.min(...corners.map((point) => point.x)), right: Math.max(...corners.map((point) => point.x)), top: Math.min(...corners.map((point) => point.y)), bottom: Math.max(...corners.map((point) => point.y)) } }; }
  get stats() { const render = this.renderer.info.render, memory = this.renderer.info.memory, projected = this.projectedDeck(); return { drawCalls: render.calls, triangles: render.triangles, pixels: (this.canvas.width || 0) * (this.canvas.height || 0), software: this.software, frames: this.frame, structureCount: this.structureCount, residentCount: this.residentCount, boatRoll: this.boatRoll, boatPitch: this.boatPitch, tankPosition: { x: this.tank.position.x, z: this.tank.position.z }, seaLevel: SEA_LEVEL(), cellCenters: projected.cells, deckBounds: projected.bounds, geometries: memory.geometries, textures: memory.textures }; }
  dispose() { this.resizeObserver?.disconnect(); this.resizeObserver = null; this.clearDynamic(); disposeObject(this.boat); disposeObject(this.world); this.renderer.dispose(); }
}

export function createScene(container) { return new TenderScene(container); }
export default createScene;
